matrix:
  include:
    - language: java
      jdk: openjdk11
      before_script:
        - cd backend/

    - language: node_js
      node_js: "10"
      sudo: required
      addons:
        chrome: stable
      before_script:
        - npm install
      script:
        - npm run lint
        - npm run build --prod
        - npm run e2e
        - npm run test-headless

      after_success:
        - curl -s https://codecov.io/bash | bash
