version: '3.7'
volumes:
  pg_db:

services:

  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379

  db:
    image: postgres:9.5-alpine
    restart: always
    volumes:
        - pg_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=v2gdemo
      - POSTGRES_USER=v2gdemo
      - POSTGRES_DB=v2gdemo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432